#!/usr/local/bin/node

var glob = require('glob'),
	fs = require('fs'),
	path = require('path');

var destination = path.join(process.env.HOME, '/Development/dotfiles-test');

// Find symlinks
glob('*/*.symlink', function (err, matches) {
	matches.forEach( function (match) {
		var fileName, filePath, target;

		// Remove / from the end if it is present
		match = match.replace(/^(.+[^\/])\/?/, '$1');

		fileName = match.split('/').slice(-1)[0].split('.symlink')[0];
		filePath = path.join( process.cwd(), match );
		target = path.join(destination, '/', fileName);

		fs.symlinkSync(filePath, target);
	});
});

